apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-daemonset
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels: 
        app: my-app
        type: front-end
    spec: 
      containers: 
      - image: nginx
        name: nginx-container
  #replicas: 3
  selector: 
    matchLabels: 
      type: front-end

